FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["Players/Players.csproj", "Players/"]
RUN dotnet restore "Players/Players.csproj"
COPY . .
WORKDIR "/src/Players"
RUN dotnet build "Players.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Players.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Players.dll"]